/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AccessControlModule {
  export type ExecutorRoleStruct = {
    executor: AddressLike;
    active: boolean;
    maxPerExecution: BigNumberish;
    maxPerDay: BigNumberish;
    maxTotal: BigNumberish;
    spentToday: BigNumberish;
    spentTotal: BigNumberish;
    lastDayReset: BigNumberish;
  };

  export type ExecutorRoleStructOutput = [
    executor: string,
    active: boolean,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint,
    spentToday: bigint,
    spentTotal: bigint,
    lastDayReset: bigint
  ] & {
    executor: string;
    active: boolean;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
    spentToday: bigint;
    spentTotal: bigint;
    lastDayReset: bigint;
  };
}

export interface TestAccessControlVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "enforceSpendingLimit"
      | "getAllExecutors"
      | "getExecutor"
      | "getExecutorInfo"
      | "isExecutorActive"
      | "owner"
      | "revokeExecutor"
      | "setExecutor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutorAdded"
      | "ExecutorRemoved"
      | "ExecutorRevoked"
      | "SpendingLimitUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "enforceSpendingLimit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllExecutors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutorInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutorActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "revokeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutor",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "enforceSpendingLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isExecutorActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutor",
    data: BytesLike
  ): Result;
}

export namespace ExecutorAddedEvent {
  export type InputTuple = [
    executor: AddressLike,
    maxPerExecution: BigNumberish,
    maxPerDay: BigNumberish,
    maxTotal: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint
  ];
  export interface OutputObject {
    executor: string;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRemovedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRevokedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendingLimitUpdatedEvent {
  export type InputTuple = [
    executor: AddressLike,
    maxPerExecution: BigNumberish,
    maxPerDay: BigNumberish,
    maxTotal: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint
  ];
  export interface OutputObject {
    executor: string;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TestAccessControlVault extends BaseContract {
  connect(runner?: ContractRunner | null): TestAccessControlVault;
  waitForDeployment(): Promise<this>;

  interface: TestAccessControlVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  enforceSpendingLimit: TypedContractMethod<
    [executor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllExecutors: TypedContractMethod<[], [string[]], "view">;

  getExecutor: TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;

  getExecutorInfo: TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;

  isExecutorActive: TypedContractMethod<
    [executor: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  revokeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  setExecutor: TypedContractMethod<
    [
      executor: AddressLike,
      maxPerExecution: BigNumberish,
      maxPerDay: BigNumberish,
      maxTotal: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "enforceSpendingLimit"
  ): TypedContractMethod<
    [executor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllExecutors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getExecutor"
  ): TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExecutorInfo"
  ): TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isExecutorActive"
  ): TypedContractMethod<[executor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "revokeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExecutor"
  ): TypedContractMethod<
    [
      executor: AddressLike,
      maxPerExecution: BigNumberish,
      maxPerDay: BigNumberish,
      maxTotal: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExecutorAdded"
  ): TypedContractEvent<
    ExecutorAddedEvent.InputTuple,
    ExecutorAddedEvent.OutputTuple,
    ExecutorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRemoved"
  ): TypedContractEvent<
    ExecutorRemovedEvent.InputTuple,
    ExecutorRemovedEvent.OutputTuple,
    ExecutorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRevoked"
  ): TypedContractEvent<
    ExecutorRevokedEvent.InputTuple,
    ExecutorRevokedEvent.OutputTuple,
    ExecutorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SpendingLimitUpdated"
  ): TypedContractEvent<
    SpendingLimitUpdatedEvent.InputTuple,
    SpendingLimitUpdatedEvent.OutputTuple,
    SpendingLimitUpdatedEvent.OutputObject
  >;

  filters: {
    "ExecutorAdded(address,uint256,uint256,uint256)": TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;
    ExecutorAdded: TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;

    "ExecutorRemoved(address)": TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;
    ExecutorRemoved: TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;

    "ExecutorRevoked(address)": TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;
    ExecutorRevoked: TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;

    "SpendingLimitUpdated(address,uint256,uint256,uint256)": TypedContractEvent<
      SpendingLimitUpdatedEvent.InputTuple,
      SpendingLimitUpdatedEvent.OutputTuple,
      SpendingLimitUpdatedEvent.OutputObject
    >;
    SpendingLimitUpdated: TypedContractEvent<
      SpendingLimitUpdatedEvent.InputTuple,
      SpendingLimitUpdatedEvent.OutputTuple,
      SpendingLimitUpdatedEvent.OutputObject
    >;
  };
}
