/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRewardManager {
  export type RewardCalculationStruct = {
    executorReward: BigNumberish;
    platformFee: BigNumberish;
    gasReimbursement: BigNumberish;
    totalFromVault: BigNumberish;
  };

  export type RewardCalculationStructOutput = [
    executorReward: bigint,
    platformFee: bigint,
    gasReimbursement: bigint,
    totalFromVault: bigint
  ] & {
    executorReward: bigint;
    platformFee: bigint;
    gasReimbursement: bigint;
    totalFromVault: bigint;
  };
}

export interface IRewardManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateReward"
      | "collectFees"
      | "distributeReward"
      | "getMaxGasReimbursement"
      | "getPlatformFeePercentage"
      | "setPlatformFee"
      | "totalFeesCollected"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PlatformFeeCollected"
      | "PlatformFeeUpdated"
      | "RewardDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "calculateReward",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxGasReimbursement",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxGasReimbursement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
}

export namespace PlatformFeeCollectedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    automationId: BigNumberish,
    executor: AddressLike,
    executorReward: BigNumberish,
    platformFee: BigNumberish,
    gasReimbursement: BigNumberish
  ];
  export type OutputTuple = [
    automationId: bigint,
    executor: string,
    executorReward: bigint,
    platformFee: bigint,
    gasReimbursement: bigint
  ];
  export interface OutputObject {
    automationId: bigint;
    executor: string;
    executorReward: bigint;
    platformFee: bigint;
    gasReimbursement: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IRewardManager extends BaseContract {
  connect(runner?: ContractRunner | null): IRewardManager;
  waitForDeployment(): Promise<this>;

  interface: IRewardManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateReward: TypedContractMethod<
    [baseReward: BigNumberish, executor: AddressLike, gasUsed: BigNumberish],
    [IRewardManager.RewardCalculationStructOutput],
    "view"
  >;

  collectFees: TypedContractMethod<
    [recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  distributeReward: TypedContractMethod<
    [
      vault: AddressLike,
      executor: AddressLike,
      baseReward: BigNumberish,
      gasUsed: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getMaxGasReimbursement: TypedContractMethod<[], [bigint], "view">;

  getPlatformFeePercentage: TypedContractMethod<[], [bigint], "view">;

  setPlatformFee: TypedContractMethod<
    [feePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateReward"
  ): TypedContractMethod<
    [baseReward: BigNumberish, executor: AddressLike, gasUsed: BigNumberish],
    [IRewardManager.RewardCalculationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[recipient: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      executor: AddressLike,
      baseReward: BigNumberish,
      gasUsed: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMaxGasReimbursement"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlatformFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[feePercentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "PlatformFeeCollected"
  ): TypedContractEvent<
    PlatformFeeCollectedEvent.InputTuple,
    PlatformFeeCollectedEvent.OutputTuple,
    PlatformFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;

  filters: {
    "PlatformFeeCollected(address,uint256)": TypedContractEvent<
      PlatformFeeCollectedEvent.InputTuple,
      PlatformFeeCollectedEvent.OutputTuple,
      PlatformFeeCollectedEvent.OutputObject
    >;
    PlatformFeeCollected: TypedContractEvent<
      PlatformFeeCollectedEvent.InputTuple,
      PlatformFeeCollectedEvent.OutputTuple,
      PlatformFeeCollectedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "RewardDistributed(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
  };
}
