/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardManager,
  IRewardManagerInterface,
} from "../../../../contracts/core/ExecutorHub.sol/IRewardManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "vault",
        type: "address",
      },
      {
        internalType: "address",
        name: "executor",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "baseReward",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasUsed",
        type: "uint256",
      },
    ],
    name: "distributeReward",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRewardManager__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardManagerInterface {
    return new Interface(_abi) as IRewardManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRewardManager {
    return new Contract(address, _abi, runner) as unknown as IRewardManager;
  }
}
