/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace BaseVault {
  export type AutomationStruct = {
    id: BigNumberish;
    strategy: AddressLike;
    params: BytesLike;
    status: BigNumberish;
    createdAt: BigNumberish;
    executionCount: BigNumberish;
    lastExecutionTime: BigNumberish;
    maxExecutions: BigNumberish;
  };

  export type AutomationStructOutput = [
    id: bigint,
    strategy: string,
    params: string,
    status: bigint,
    createdAt: bigint,
    executionCount: bigint,
    lastExecutionTime: bigint,
    maxExecutions: bigint
  ] & {
    id: bigint;
    strategy: string;
    params: string;
    status: bigint;
    createdAt: bigint;
    executionCount: bigint;
    lastExecutionTime: bigint;
    maxExecutions: bigint;
  };
}

export interface BaseVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelAutomation"
      | "createAutomation"
      | "executorHub"
      | "getAutomation"
      | "getAutomations"
      | "nextAutomationId"
      | "nonce"
      | "strategyRegistry"
      | "triggerAutomation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutomationCancelled"
      | "AutomationCompleted"
      | "AutomationCreated"
      | "AutomationTriggered"
      | "StrategyExecuted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelAutomation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAutomation",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executorHub",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAutomation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAutomations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextAutomationId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "strategyRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerAutomation",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executorHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAutomations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextAutomationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strategyRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerAutomation",
    data: BytesLike
  ): Result;
}

export namespace AutomationCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationCompletedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationCreatedEvent {
  export type InputTuple = [id: BigNumberish, strategy: AddressLike];
  export type OutputTuple = [id: bigint, strategy: string];
  export interface OutputObject {
    id: bigint;
    strategy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationTriggeredEvent {
  export type InputTuple = [
    id: BigNumberish,
    success: boolean,
    executionCount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    success: boolean,
    executionCount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    success: boolean;
    executionCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyExecutedEvent {
  export type InputTuple = [
    strategy: AddressLike,
    success: boolean,
    nonce: BigNumberish
  ];
  export type OutputTuple = [strategy: string, success: boolean, nonce: bigint];
  export interface OutputObject {
    strategy: string;
    success: boolean;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BaseVault extends BaseContract {
  connect(runner?: ContractRunner | null): BaseVault;
  waitForDeployment(): Promise<this>;

  interface: BaseVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelAutomation: TypedContractMethod<
    [automationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createAutomation: TypedContractMethod<
    [strategy: AddressLike, params: BytesLike, maxExecutions: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  executorHub: TypedContractMethod<[], [string], "view">;

  getAutomation: TypedContractMethod<
    [id: BigNumberish],
    [BaseVault.AutomationStructOutput],
    "view"
  >;

  getAutomations: TypedContractMethod<
    [],
    [BaseVault.AutomationStructOutput[]],
    "view"
  >;

  nextAutomationId: TypedContractMethod<[], [bigint], "view">;

  nonce: TypedContractMethod<[], [bigint], "view">;

  strategyRegistry: TypedContractMethod<[], [string], "view">;

  triggerAutomation: TypedContractMethod<
    [automationId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelAutomation"
  ): TypedContractMethod<[automationId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAutomation"
  ): TypedContractMethod<
    [strategy: AddressLike, params: BytesLike, maxExecutions: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executorHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAutomation"
  ): TypedContractMethod<
    [id: BigNumberish],
    [BaseVault.AutomationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAutomations"
  ): TypedContractMethod<[], [BaseVault.AutomationStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "nextAutomationId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "strategyRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "triggerAutomation"
  ): TypedContractMethod<[automationId: BigNumberish], [boolean], "nonpayable">;

  getEvent(
    key: "AutomationCancelled"
  ): TypedContractEvent<
    AutomationCancelledEvent.InputTuple,
    AutomationCancelledEvent.OutputTuple,
    AutomationCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AutomationCompleted"
  ): TypedContractEvent<
    AutomationCompletedEvent.InputTuple,
    AutomationCompletedEvent.OutputTuple,
    AutomationCompletedEvent.OutputObject
  >;
  getEvent(
    key: "AutomationCreated"
  ): TypedContractEvent<
    AutomationCreatedEvent.InputTuple,
    AutomationCreatedEvent.OutputTuple,
    AutomationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AutomationTriggered"
  ): TypedContractEvent<
    AutomationTriggeredEvent.InputTuple,
    AutomationTriggeredEvent.OutputTuple,
    AutomationTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "StrategyExecuted"
  ): TypedContractEvent<
    StrategyExecutedEvent.InputTuple,
    StrategyExecutedEvent.OutputTuple,
    StrategyExecutedEvent.OutputObject
  >;

  filters: {
    "AutomationCancelled(uint256)": TypedContractEvent<
      AutomationCancelledEvent.InputTuple,
      AutomationCancelledEvent.OutputTuple,
      AutomationCancelledEvent.OutputObject
    >;
    AutomationCancelled: TypedContractEvent<
      AutomationCancelledEvent.InputTuple,
      AutomationCancelledEvent.OutputTuple,
      AutomationCancelledEvent.OutputObject
    >;

    "AutomationCompleted(uint256)": TypedContractEvent<
      AutomationCompletedEvent.InputTuple,
      AutomationCompletedEvent.OutputTuple,
      AutomationCompletedEvent.OutputObject
    >;
    AutomationCompleted: TypedContractEvent<
      AutomationCompletedEvent.InputTuple,
      AutomationCompletedEvent.OutputTuple,
      AutomationCompletedEvent.OutputObject
    >;

    "AutomationCreated(uint256,address)": TypedContractEvent<
      AutomationCreatedEvent.InputTuple,
      AutomationCreatedEvent.OutputTuple,
      AutomationCreatedEvent.OutputObject
    >;
    AutomationCreated: TypedContractEvent<
      AutomationCreatedEvent.InputTuple,
      AutomationCreatedEvent.OutputTuple,
      AutomationCreatedEvent.OutputObject
    >;

    "AutomationTriggered(uint256,bool,uint256)": TypedContractEvent<
      AutomationTriggeredEvent.InputTuple,
      AutomationTriggeredEvent.OutputTuple,
      AutomationTriggeredEvent.OutputObject
    >;
    AutomationTriggered: TypedContractEvent<
      AutomationTriggeredEvent.InputTuple,
      AutomationTriggeredEvent.OutputTuple,
      AutomationTriggeredEvent.OutputObject
    >;

    "StrategyExecuted(address,bool,uint256)": TypedContractEvent<
      StrategyExecutedEvent.InputTuple,
      StrategyExecutedEvent.OutputTuple,
      StrategyExecutedEvent.OutputObject
    >;
    StrategyExecuted: TypedContractEvent<
      StrategyExecutedEvent.InputTuple,
      StrategyExecutedEvent.OutputTuple,
      StrategyExecutedEvent.OutputObject
    >;
  };
}
