/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace ExecutorHub {
  export type ExecutorStruct = {
    addr: AddressLike;
    isActive: boolean;
    totalExecutions: BigNumberish;
    successfulExecutions: BigNumberish;
    failedExecutions: BigNumberish;
  };

  export type ExecutorStructOutput = [
    addr: string,
    isActive: boolean,
    totalExecutions: bigint,
    successfulExecutions: bigint,
    failedExecutions: bigint
  ] & {
    addr: string;
    isActive: boolean;
    totalExecutions: bigint;
    successfulExecutions: bigint;
    failedExecutions: bigint;
  };

  export type TaskStruct = {
    vault: AddressLike;
    automationId: BigNumberish;
    strategy: AddressLike;
    params: BytesLike;
    active: boolean;
  };

  export type TaskStructOutput = [
    vault: string,
    automationId: bigint,
    strategy: string,
    params: string,
    active: boolean
  ] & {
    vault: string;
    automationId: bigint;
    strategy: string;
    params: string;
    active: boolean;
  };
}

export interface ExecutorHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addExecutor"
      | "baseRewardPerExecution"
      | "executeAutomation"
      | "executorIndex"
      | "executorList"
      | "executors"
      | "getAllExecutors"
      | "getExecutor"
      | "getTasks"
      | "isExecutor"
      | "owner"
      | "registerTask"
      | "removeExecutor"
      | "removeTask"
      | "renounceOwnership"
      | "rewardManager"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutomationExecuted"
      | "ExecutorAdded"
      | "ExecutorRemoved"
      | "OwnershipTransferred"
      | "TaskRegistered"
      | "TaskRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "baseRewardPerExecution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeAutomation",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executorIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executorList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllExecutors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getTasks", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerTask",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "baseRewardPerExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executorIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executorList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTasks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExecutor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AutomationExecutedEvent {
  export type InputTuple = [
    vault: AddressLike,
    automationId: BigNumberish,
    executor: AddressLike,
    success: boolean
  ];
  export type OutputTuple = [
    vault: string,
    automationId: bigint,
    executor: string,
    success: boolean
  ];
  export interface OutputObject {
    vault: string;
    automationId: bigint;
    executor: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorAddedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRemovedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRegisteredEvent {
  export type InputTuple = [
    vault: AddressLike,
    automationId: BigNumberish,
    strategy: AddressLike
  ];
  export type OutputTuple = [
    vault: string,
    automationId: bigint,
    strategy: string
  ];
  export interface OutputObject {
    vault: string;
    automationId: bigint;
    strategy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRemovedEvent {
  export type InputTuple = [vault: AddressLike, automationId: BigNumberish];
  export type OutputTuple = [vault: string, automationId: bigint];
  export interface OutputObject {
    vault: string;
    automationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExecutorHub extends BaseContract {
  connect(runner?: ContractRunner | null): ExecutorHub;
  waitForDeployment(): Promise<this>;

  interface: ExecutorHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  baseRewardPerExecution: TypedContractMethod<[], [bigint], "view">;

  executeAutomation: TypedContractMethod<
    [vault: AddressLike, automationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executorIndex: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  executorList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  executors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint, bigint] & {
        addr: string;
        isActive: boolean;
        totalExecutions: bigint;
        successfulExecutions: bigint;
        failedExecutions: bigint;
      }
    ],
    "view"
  >;

  getAllExecutors: TypedContractMethod<[], [string[]], "view">;

  getExecutor: TypedContractMethod<
    [account: AddressLike],
    [ExecutorHub.ExecutorStructOutput],
    "view"
  >;

  getTasks: TypedContractMethod<[], [ExecutorHub.TaskStructOutput[]], "view">;

  isExecutor: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  registerTask: TypedContractMethod<
    [automationId: BigNumberish, strategy: AddressLike, params: BytesLike],
    [void],
    "nonpayable"
  >;

  removeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  removeTask: TypedContractMethod<
    [automationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rewardManager: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "baseRewardPerExecution"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeAutomation"
  ): TypedContractMethod<
    [vault: AddressLike, automationId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executorIndex"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "executorList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "executors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint, bigint, bigint] & {
        addr: string;
        isActive: boolean;
        totalExecutions: bigint;
        successfulExecutions: bigint;
        failedExecutions: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllExecutors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getExecutor"
  ): TypedContractMethod<
    [account: AddressLike],
    [ExecutorHub.ExecutorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTasks"
  ): TypedContractMethod<[], [ExecutorHub.TaskStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "isExecutor"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerTask"
  ): TypedContractMethod<
    [automationId: BigNumberish, strategy: AddressLike, params: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeTask"
  ): TypedContractMethod<[automationId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rewardManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AutomationExecuted"
  ): TypedContractEvent<
    AutomationExecutedEvent.InputTuple,
    AutomationExecutedEvent.OutputTuple,
    AutomationExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorAdded"
  ): TypedContractEvent<
    ExecutorAddedEvent.InputTuple,
    ExecutorAddedEvent.OutputTuple,
    ExecutorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRemoved"
  ): TypedContractEvent<
    ExecutorRemovedEvent.InputTuple,
    ExecutorRemovedEvent.OutputTuple,
    ExecutorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TaskRegistered"
  ): TypedContractEvent<
    TaskRegisteredEvent.InputTuple,
    TaskRegisteredEvent.OutputTuple,
    TaskRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "TaskRemoved"
  ): TypedContractEvent<
    TaskRemovedEvent.InputTuple,
    TaskRemovedEvent.OutputTuple,
    TaskRemovedEvent.OutputObject
  >;

  filters: {
    "AutomationExecuted(address,uint256,address,bool)": TypedContractEvent<
      AutomationExecutedEvent.InputTuple,
      AutomationExecutedEvent.OutputTuple,
      AutomationExecutedEvent.OutputObject
    >;
    AutomationExecuted: TypedContractEvent<
      AutomationExecutedEvent.InputTuple,
      AutomationExecutedEvent.OutputTuple,
      AutomationExecutedEvent.OutputObject
    >;

    "ExecutorAdded(address)": TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;
    ExecutorAdded: TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;

    "ExecutorRemoved(address)": TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;
    ExecutorRemoved: TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TaskRegistered(address,uint256,address)": TypedContractEvent<
      TaskRegisteredEvent.InputTuple,
      TaskRegisteredEvent.OutputTuple,
      TaskRegisteredEvent.OutputObject
    >;
    TaskRegistered: TypedContractEvent<
      TaskRegisteredEvent.InputTuple,
      TaskRegisteredEvent.OutputTuple,
      TaskRegisteredEvent.OutputObject
    >;

    "TaskRemoved(address,uint256)": TypedContractEvent<
      TaskRemovedEvent.InputTuple,
      TaskRemovedEvent.OutputTuple,
      TaskRemovedEvent.OutputObject
    >;
    TaskRemoved: TypedContractEvent<
      TaskRemovedEvent.InputTuple,
      TaskRemovedEvent.OutputTuple,
      TaskRemovedEvent.OutputObject
    >;
  };
}
