/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AccessControlModule {
  export type ExecutorRoleStruct = {
    executor: AddressLike;
    active: boolean;
    maxPerExecution: BigNumberish;
    maxPerDay: BigNumberish;
    maxTotal: BigNumberish;
    spentToday: BigNumberish;
    spentTotal: BigNumberish;
    lastDayReset: BigNumberish;
  };

  export type ExecutorRoleStructOutput = [
    executor: string,
    active: boolean,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint,
    spentToday: bigint,
    spentTotal: bigint,
    lastDayReset: bigint
  ] & {
    executor: string;
    active: boolean;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
    spentToday: bigint;
    spentTotal: bigint;
    lastDayReset: bigint;
  };
}

export interface SharedAccountModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asset"
      | "balanceOf"
      | "deposit"
      | "getAllExecutors"
      | "getExecutor"
      | "redeem"
      | "sharePrice"
      | "totalAssets"
      | "totalShares"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Deposit"
      | "ExecutorAdded"
      | "ExecutorRemoved"
      | "ExecutorRevoked"
      | "ManagerSet"
      | "Redeem"
      | "SpendingLimitUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllExecutors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sharePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sharePrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    sharesIssued: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    sharesIssued: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    sharesIssued: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorAddedEvent {
  export type InputTuple = [
    executor: AddressLike,
    maxPerExecution: BigNumberish,
    maxPerDay: BigNumberish,
    maxTotal: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint
  ];
  export interface OutputObject {
    executor: string;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRemovedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRevokedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManagerSetEvent {
  export type InputTuple = [manager: AddressLike];
  export type OutputTuple = [manager: string];
  export interface OutputObject {
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemEvent {
  export type InputTuple = [
    user: AddressLike,
    sharesBurned: BigNumberish,
    assetReturned: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    sharesBurned: bigint,
    assetReturned: bigint
  ];
  export interface OutputObject {
    user: string;
    sharesBurned: bigint;
    assetReturned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendingLimitUpdatedEvent {
  export type InputTuple = [
    executor: AddressLike,
    maxPerExecution: BigNumberish,
    maxPerDay: BigNumberish,
    maxTotal: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint
  ];
  export interface OutputObject {
    executor: string;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SharedAccountModule extends BaseContract {
  connect(runner?: ContractRunner | null): SharedAccountModule;
  waitForDeployment(): Promise<this>;

  interface: SharedAccountModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asset: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;

  getAllExecutors: TypedContractMethod<[], [string[]], "view">;

  getExecutor: TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;

  redeem: TypedContractMethod<[shares: BigNumberish], [bigint], "nonpayable">;

  sharePrice: TypedContractMethod<[], [bigint], "view">;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllExecutors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getExecutor"
  ): TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "sharePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorAdded"
  ): TypedContractEvent<
    ExecutorAddedEvent.InputTuple,
    ExecutorAddedEvent.OutputTuple,
    ExecutorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRemoved"
  ): TypedContractEvent<
    ExecutorRemovedEvent.InputTuple,
    ExecutorRemovedEvent.OutputTuple,
    ExecutorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRevoked"
  ): TypedContractEvent<
    ExecutorRevokedEvent.InputTuple,
    ExecutorRevokedEvent.OutputTuple,
    ExecutorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ManagerSet"
  ): TypedContractEvent<
    ManagerSetEvent.InputTuple,
    ManagerSetEvent.OutputTuple,
    ManagerSetEvent.OutputObject
  >;
  getEvent(
    key: "Redeem"
  ): TypedContractEvent<
    RedeemEvent.InputTuple,
    RedeemEvent.OutputTuple,
    RedeemEvent.OutputObject
  >;
  getEvent(
    key: "SpendingLimitUpdated"
  ): TypedContractEvent<
    SpendingLimitUpdatedEvent.InputTuple,
    SpendingLimitUpdatedEvent.OutputTuple,
    SpendingLimitUpdatedEvent.OutputObject
  >;

  filters: {
    "Deposit(address,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "ExecutorAdded(address,uint256,uint256,uint256)": TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;
    ExecutorAdded: TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;

    "ExecutorRemoved(address)": TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;
    ExecutorRemoved: TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;

    "ExecutorRevoked(address)": TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;
    ExecutorRevoked: TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;

    "ManagerSet(address)": TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;
    ManagerSet: TypedContractEvent<
      ManagerSetEvent.InputTuple,
      ManagerSetEvent.OutputTuple,
      ManagerSetEvent.OutputObject
    >;

    "Redeem(address,uint256,uint256)": TypedContractEvent<
      RedeemEvent.InputTuple,
      RedeemEvent.OutputTuple,
      RedeemEvent.OutputObject
    >;
    Redeem: TypedContractEvent<
      RedeemEvent.InputTuple,
      RedeemEvent.OutputTuple,
      RedeemEvent.OutputObject
    >;

    "SpendingLimitUpdated(address,uint256,uint256,uint256)": TypedContractEvent<
      SpendingLimitUpdatedEvent.InputTuple,
      SpendingLimitUpdatedEvent.OutputTuple,
      SpendingLimitUpdatedEvent.OutputObject
    >;
    SpendingLimitUpdated: TypedContractEvent<
      SpendingLimitUpdatedEvent.InputTuple,
      SpendingLimitUpdatedEvent.OutputTuple,
      SpendingLimitUpdatedEvent.OutputObject
    >;
  };
}
