/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AccessControlModule {
  export type ExecutorRoleStruct = {
    executor: AddressLike;
    active: boolean;
    maxPerExecution: BigNumberish;
    maxPerDay: BigNumberish;
    maxTotal: BigNumberish;
    spentToday: BigNumberish;
    spentTotal: BigNumberish;
    lastDayReset: BigNumberish;
  };

  export type ExecutorRoleStructOutput = [
    executor: string,
    active: boolean,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint,
    spentToday: bigint,
    spentTotal: bigint,
    lastDayReset: bigint
  ] & {
    executor: string;
    active: boolean;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
    spentToday: bigint;
    spentTotal: bigint;
    lastDayReset: bigint;
  };
}

export interface SharedAccountModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "asset"
      | "balanceOf"
      | "balanceOfAssets"
      | "claimWithdrawal"
      | "deployedCapital"
      | "deposit"
      | "fulfillWithdrawal"
      | "getAllExecutors"
      | "getExecutor"
      | "getRequest"
      | "getUserPosition"
      | "getUserRequests"
      | "highWaterMark"
      | "initialPendingShares"
      | "liquidAssets"
      | "pendingWithdrawalNAV"
      | "pendingWithdrawalShares"
      | "realizedGains"
      | "requestWithdrawal"
      | "sharePrice"
      | "totalAssets"
      | "totalCapitalDeposited"
      | "totalShares"
      | "updateDeployedCapital"
      | "withdrawalRequestCount"
      | "withdrawalRequests"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeployedCapitalUpdated"
      | "Deposit"
      | "ExecutorAdded"
      | "ExecutorRemoved"
      | "ExecutorRevoked"
      | "SpendingLimitUpdated"
      | "WithdrawalClaimed"
      | "WithdrawalFulfilled"
      | "WithdrawalRequested"
  ): EventFragment;

  encodeFunctionData(functionFragment: "asset", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfAssets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deployedCapital",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fulfillWithdrawal",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllExecutors",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPosition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRequests",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "highWaterMark",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialPendingShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawalNAV",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "realizedGains",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sharePrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAssets",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalCapitalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateDeployedCapital",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequests",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "asset", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployedCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserPosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "highWaterMark",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialPendingShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawalNAV",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "realizedGains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sharePrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAssets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalCapitalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateDeployedCapital",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequests",
    data: BytesLike
  ): Result;
}

export namespace DeployedCapitalUpdatedEvent {
  export type InputTuple = [oldAmount: BigNumberish, newAmount: BigNumberish];
  export type OutputTuple = [oldAmount: bigint, newAmount: bigint];
  export interface OutputObject {
    oldAmount: bigint;
    newAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    assets: BigNumberish,
    shares: BigNumberish,
    sharePrice: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    assets: bigint,
    shares: bigint,
    sharePrice: bigint
  ];
  export interface OutputObject {
    user: string;
    assets: bigint;
    shares: bigint;
    sharePrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorAddedEvent {
  export type InputTuple = [
    executor: AddressLike,
    maxPerExecution: BigNumberish,
    maxPerDay: BigNumberish,
    maxTotal: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint
  ];
  export interface OutputObject {
    executor: string;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRemovedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRevokedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendingLimitUpdatedEvent {
  export type InputTuple = [
    executor: AddressLike,
    maxPerExecution: BigNumberish,
    maxPerDay: BigNumberish,
    maxTotal: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint
  ];
  export interface OutputObject {
    executor: string;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalClaimedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    assets: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, assets: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    assets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFulfilledEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    assets: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, assets: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    assets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalRequestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    shares: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, shares: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    shares: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SharedAccountModule extends BaseContract {
  connect(runner?: ContractRunner | null): SharedAccountModule;
  waitForDeployment(): Promise<this>;

  interface: SharedAccountModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  asset: TypedContractMethod<[], [string], "view">;

  balanceOf: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  balanceOfAssets: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  claimWithdrawal: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  deployedCapital: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;

  fulfillWithdrawal: TypedContractMethod<
    [id: BigNumberish, assetAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllExecutors: TypedContractMethod<[], [string[]], "view">;

  getExecutor: TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;

  getRequest: TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        user: string;
        shares: bigint;
        assetAmount: bigint;
        requestTime: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getUserPosition: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        currentValue: bigint;
        pendingRequests: bigint;
      }
    ],
    "view"
  >;

  getUserRequests: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  highWaterMark: TypedContractMethod<[], [bigint], "view">;

  initialPendingShares: TypedContractMethod<[], [bigint], "view">;

  liquidAssets: TypedContractMethod<[], [bigint], "view">;

  pendingWithdrawalNAV: TypedContractMethod<[], [bigint], "view">;

  pendingWithdrawalShares: TypedContractMethod<[], [bigint], "view">;

  realizedGains: TypedContractMethod<[], [bigint], "view">;

  requestWithdrawal: TypedContractMethod<
    [shares: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  sharePrice: TypedContractMethod<[], [bigint], "view">;

  totalAssets: TypedContractMethod<[], [bigint], "view">;

  totalCapitalDeposited: TypedContractMethod<[], [bigint], "view">;

  totalShares: TypedContractMethod<[], [bigint], "view">;

  updateDeployedCapital: TypedContractMethod<
    [newAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawalRequestCount: TypedContractMethod<[], [bigint], "view">;

  withdrawalRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        user: string;
        shares: bigint;
        assetAmount: bigint;
        requestTime: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "asset"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfAssets"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimWithdrawal"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deployedCapital"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "fulfillWithdrawal"
  ): TypedContractMethod<
    [id: BigNumberish, assetAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllExecutors"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getExecutor"
  ): TypedContractMethod<
    [executor: AddressLike],
    [AccessControlModule.ExecutorRoleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [id: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        user: string;
        shares: bigint;
        assetAmount: bigint;
        requestTime: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPosition"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        shares: bigint;
        currentValue: bigint;
        pendingRequests: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserRequests"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "highWaterMark"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "initialPendingShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawalNAV"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawalShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "realizedGains"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestWithdrawal"
  ): TypedContractMethod<[shares: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "sharePrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAssets"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalCapitalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateDeployedCapital"
  ): TypedContractMethod<[newAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawalRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawalRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        user: string;
        shares: bigint;
        assetAmount: bigint;
        requestTime: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DeployedCapitalUpdated"
  ): TypedContractEvent<
    DeployedCapitalUpdatedEvent.InputTuple,
    DeployedCapitalUpdatedEvent.OutputTuple,
    DeployedCapitalUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorAdded"
  ): TypedContractEvent<
    ExecutorAddedEvent.InputTuple,
    ExecutorAddedEvent.OutputTuple,
    ExecutorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRemoved"
  ): TypedContractEvent<
    ExecutorRemovedEvent.InputTuple,
    ExecutorRemovedEvent.OutputTuple,
    ExecutorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRevoked"
  ): TypedContractEvent<
    ExecutorRevokedEvent.InputTuple,
    ExecutorRevokedEvent.OutputTuple,
    ExecutorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "SpendingLimitUpdated"
  ): TypedContractEvent<
    SpendingLimitUpdatedEvent.InputTuple,
    SpendingLimitUpdatedEvent.OutputTuple,
    SpendingLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalClaimed"
  ): TypedContractEvent<
    WithdrawalClaimedEvent.InputTuple,
    WithdrawalClaimedEvent.OutputTuple,
    WithdrawalClaimedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalFulfilled"
  ): TypedContractEvent<
    WithdrawalFulfilledEvent.InputTuple,
    WithdrawalFulfilledEvent.OutputTuple,
    WithdrawalFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalRequested"
  ): TypedContractEvent<
    WithdrawalRequestedEvent.InputTuple,
    WithdrawalRequestedEvent.OutputTuple,
    WithdrawalRequestedEvent.OutputObject
  >;

  filters: {
    "DeployedCapitalUpdated(uint256,uint256)": TypedContractEvent<
      DeployedCapitalUpdatedEvent.InputTuple,
      DeployedCapitalUpdatedEvent.OutputTuple,
      DeployedCapitalUpdatedEvent.OutputObject
    >;
    DeployedCapitalUpdated: TypedContractEvent<
      DeployedCapitalUpdatedEvent.InputTuple,
      DeployedCapitalUpdatedEvent.OutputTuple,
      DeployedCapitalUpdatedEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "ExecutorAdded(address,uint256,uint256,uint256)": TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;
    ExecutorAdded: TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;

    "ExecutorRemoved(address)": TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;
    ExecutorRemoved: TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;

    "ExecutorRevoked(address)": TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;
    ExecutorRevoked: TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;

    "SpendingLimitUpdated(address,uint256,uint256,uint256)": TypedContractEvent<
      SpendingLimitUpdatedEvent.InputTuple,
      SpendingLimitUpdatedEvent.OutputTuple,
      SpendingLimitUpdatedEvent.OutputObject
    >;
    SpendingLimitUpdated: TypedContractEvent<
      SpendingLimitUpdatedEvent.InputTuple,
      SpendingLimitUpdatedEvent.OutputTuple,
      SpendingLimitUpdatedEvent.OutputObject
    >;

    "WithdrawalClaimed(uint256,address,uint256)": TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;
    WithdrawalClaimed: TypedContractEvent<
      WithdrawalClaimedEvent.InputTuple,
      WithdrawalClaimedEvent.OutputTuple,
      WithdrawalClaimedEvent.OutputObject
    >;

    "WithdrawalFulfilled(uint256,address,uint256)": TypedContractEvent<
      WithdrawalFulfilledEvent.InputTuple,
      WithdrawalFulfilledEvent.OutputTuple,
      WithdrawalFulfilledEvent.OutputObject
    >;
    WithdrawalFulfilled: TypedContractEvent<
      WithdrawalFulfilledEvent.InputTuple,
      WithdrawalFulfilledEvent.OutputTuple,
      WithdrawalFulfilledEvent.OutputObject
    >;

    "WithdrawalRequested(uint256,address,uint256)": TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
    WithdrawalRequested: TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
  };
}
