/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IExecutorHub,
  IExecutorHubInterface,
} from "../../../../contracts/core/BaseVault.sol/IExecutorHub";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "strategy",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "params",
        type: "bytes",
      },
    ],
    name: "registerTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "removeTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IExecutorHub__factory {
  static readonly abi = _abi;
  static createInterface(): IExecutorHubInterface {
    return new Interface(_abi) as IExecutorHubInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IExecutorHub {
    return new Contract(address, _abi, runner) as unknown as IExecutorHub;
  }
}
