/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LendingProtocolAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canExecute"
      | "execute"
      | "getTokenRequirements"
      | "supplied"
      | "totalLP"
      | "validateParams"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ActionExecuted" | "Supplied"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canExecute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenRequirements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supplied",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "totalLP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validateParams",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supplied", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateParams",
    data: BytesLike
  ): Result;
}

export namespace ActionExecutedEvent {
  export type InputTuple = [
    vault: AddressLike,
    target: AddressLike,
    success: boolean,
    data: BytesLike
  ];
  export type OutputTuple = [
    vault: string,
    target: string,
    success: boolean,
    data: string
  ];
  export interface OutputObject {
    vault: string;
    target: string;
    success: boolean;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SuppliedEvent {
  export type InputTuple = [
    vault: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    lpMinted: BigNumberish
  ];
  export type OutputTuple = [
    vault: string,
    token: string,
    amount: bigint,
    lpMinted: bigint
  ];
  export interface OutputObject {
    vault: string;
    token: string;
    amount: bigint;
    lpMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LendingProtocolAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): LendingProtocolAdapter;
  waitForDeployment(): Promise<this>;

  interface: LendingProtocolAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canExecute: TypedContractMethod<
    [arg0: AddressLike, params: BytesLike],
    [[boolean, string] & { canExec: boolean; reason: string }],
    "view"
  >;

  execute: TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;

  getTokenRequirements: TypedContractMethod<
    [params: BytesLike],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;

  supplied: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalLP: TypedContractMethod<[], [bigint], "view">;

  validateParams: TypedContractMethod<
    [params: BytesLike],
    [[boolean, string] & { valid: boolean; error: string }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<
    [arg0: AddressLike, params: BytesLike],
    [[boolean, string] & { canExec: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTokenRequirements"
  ): TypedContractMethod<
    [params: BytesLike],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "supplied"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "validateParams"
  ): TypedContractMethod<
    [params: BytesLike],
    [[boolean, string] & { valid: boolean; error: string }],
    "view"
  >;

  getEvent(
    key: "ActionExecuted"
  ): TypedContractEvent<
    ActionExecutedEvent.InputTuple,
    ActionExecutedEvent.OutputTuple,
    ActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Supplied"
  ): TypedContractEvent<
    SuppliedEvent.InputTuple,
    SuppliedEvent.OutputTuple,
    SuppliedEvent.OutputObject
  >;

  filters: {
    "ActionExecuted(address,address,bool,bytes)": TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;
    ActionExecuted: TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;

    "Supplied(address,address,uint256,uint256)": TypedContractEvent<
      SuppliedEvent.InputTuple,
      SuppliedEvent.OutputTuple,
      SuppliedEvent.OutputObject
    >;
    Supplied: TypedContractEvent<
      SuppliedEvent.InputTuple,
      SuppliedEvent.OutputTuple,
      SuppliedEvent.OutputObject
    >;
  };
}
